spring:
  application:
    name: library-app
  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;
    schema: schema.sql
  banner:
    location: classpath:banner.txt
  h2:
    console:
      enabled: true