spring:
  application:
    name: library-app-hibernate
  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;
    initialization-mode: always
    schema: schema.sql
  banner:
    location: classpath:banner.txt
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    show-sql: true