spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}?ssl=true&replicaSet=atlas-k5oiu7-shard-0&authSource=admin&retryWrites=true&w=majority

logging:
  file:
    name: /tmp/logs/library/logger.log
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile, prometheus
  endpoint:
    health:
      show-details: always

