spring:
  data:
    mongodb:
      authentication-database: none
      port: 27001
      host: localhost
      database: library
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
